### ISSUE TITLE
i am getting this error while executing this command python3 main.py -train -model_dir [model_path] -num_steps 7000

### ISSUE THREAD

**Issue by HamzaAmeerHussain** [yaushian/Unparalleled-Text-summarization-using-GAN#1]
ERROR:tensorflow:Couldn't match files for checkpoint [model_path]/generator/model-20000
Traceback (most recent call last):
File "main.py", line 42, in
run(args)
File "main.py", line 34, in run
model.train()
File "/content/Unparalleled-Text-Summarization-using-GAN/seq2seq2seq.py", line 355, in train
self.generator_saver.restore(self.sess,tf.train.latest_checkpoint(gen_model_dir))
File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 1277, in restore
raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.

**Comment by yaushian** [comment]
Please check whether the file with path "[model_path]/generator/model-20000" exists. If it exists, this error should not happen.

ps. [model_path] is your desired model path.
